version: "3.7"

services:
  db:
    image: mariadb:10.11.2
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - /root/db-data:/var/lib/mysql
    networks:
      - matomo-network

  matomo:
    image: matomo:4.14.1
    restart: always
    environment:
      MATOMO_DATABASE_HOST: ${MATOMO_DATABASE_HOST}
      MATOMO_DATABASE_NAME: ${MATOMO_DATABASE_NAME}
      MATOMO_DATABASE_USER: ${MATOMO_DATABASE_USER}
      MATOMO_DATABASE_PASSWORD: ${MATOMO_DATABASE_PASSWORD}
      MATOMO_DATABASE_TABLES_PREFIX: ${MATOMO_DATABASE_TABLES_PREFIX}
    volumes:
      - /root/matomo-data:/var/www/html
    ports:
      - "8080:80"
    networks:
      - matomo-network

networks:
  matomo-network:
