version: '3'

services:
  registry:
    image: registry:2
    ports:
    - "5000:5000"
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry
      REGISTRY_AUTH_HTPASSWD_PATH: ./auth/registry.password
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /registry-data
    volumes:
      - ./auth:/auth
      - ./registry-data:/data
    restart: always

    # set up authentication
    # sudo apt install apache2-utils -y
    # mkdir ~/docker-registry/auth
    # cd ~/docker-registry/auth
    # htpasswd -Bc registry.password username